# Generated by Django 4.0.4 on 2022-05-11 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_snack_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='price',
        ),
    ]
